config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'pages#welcome', as: :welcome

  resource :feedback, only: [:new, :create]
  resources :access_requests, only: [:new, :create]

  resources :users, except: :show do
    member do
      post 'invite', to: 'invites#create', as: :invite
      get 'register/:invite_token', to: 'invites#edit', as: :rsvp
      match 'register', to: 'invites#update', via: [:patch, :put], as: :register
    end
  end

  resources :papers, except: :index do
    root to: 'trials#index'
    get 'download', on: :member, as: :download
    collection do
      get 'lookup', to: 'paper_searches#lookup', as: :lookup
      get 'search', to: 'paper_searches#search', as: :search
    end
    resources :trials
    resources :supplementals, except: [:index, :show], id: /[A-Za-z0-9\.]+?/, format: /html|js|json/
  end

  resources :supplementals, except: :show, id: /[A-Za-z0-9\.]+?/, format: /html|js|json/ do
    get 'download', on: :member, as: :download
  end

  resources :paper_summaries do
    get 'download', on: :member, as: :download
    collection do
      get 'manage', to: 'paper_summaries#manage', as: :manage
    end
  end
  get 'latest', to: 'paper_summaries#index', as: :latest_research

  resources :trials, only: :index
  resources :measures, only: [:new, :create, :edit, :update, :destroy], as: :performance_measures

  resources :sales_aids do
    get 'download', on: :member, as: :download
    collection do
      get 'manage', to: 'sales_aids#manage', as: :manage
    end
  end
  get 'learn-more', to: 'sales_aids#index', as: :learn_more

  resources :sessions, only: [:new, :create, :destroy]
  resource :password_reset, only: [:new, :create, :edit, :update]
  resource :role_impersonation, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  root to: 'pages#welcome'
end

app/models/paper_summary.rb
class PaperSummary < ActiveRecord::Base
  belongs_to :trial

  SPECIES = ['Dairy', 'Beef', 'Poultry', 'Swine', 'Equine', 'Multi-Species', 'Aqua', 'Pet', 'Specialty']

  include FileDataManagement

  mount_uploader :document, DocumentUploader
  acts_as_list scope: [:species]

  validates :title, presence: true
  validates :description, presence: true
  validates :species, presence: true, inclusion: { in: SPECIES }
  
  scope :featured, -> { where(featured: true) }
end

app/controllers/paper_summaries_controller.rb
class PaperSummariesController < ApplicationController
  before_action :set_paper_summary, only: [:edit, :update, :destroy, :download]

  def index
    authorize! PaperSummary
    @paper_summaries = PaperSummary.where(trial: policy_scope(Trial).pluck(:id)).featured.order(:species, :position).all.group_by(&:species)
  end

  def new
    @paper_summary = PaperSummary.new
    authorize! @paper_summary
  end

  def edit
  end

  def create
    @paper_summary = PaperSummary.new(paper_summary_attributes)
    authorize! @paper_summary

    if @paper_summary.save
      redirect_to latest_research_path, notice: 'Paper summary was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    respond_to do |format|
      format.html {
        if @paper_summary.update(paper_summary_attributes)
          redirect_to latest_research_path, notice: 'Paper summary was successfully updated.'
        else
          render action: 'edit'
        end
      }
      format.json {
        new_position = params[:reposition].try(:to_i)
        if new_position && @paper_summary.insert_at(new_position)
          render json: @paper_summary, status: :created, location: @paper_summary
        else
          render json: @paper_summary.errors, status: :unprocessable_entity
        end
      }
    end
  end

  def destroy
    @paper_summary.destroy
    redirect_to :back
  end

  def manage
    @paper_summaries = PaperSummary.includes(trial: :paper).order(:species, :position)
    authorize! @paper_summaries
  end

  def download
    send_data (open @paper_summary.document.url).read,
      type: @paper_summary.document.file.content_type,
      filename: @paper_summary.filename,
      disposition: 'attachment'
  end

  private
    def set_paper_summary
      @paper_summary = PaperSummary.find(params[:id])
      authorize! @paper_summary
    end

    def paper_summary_attributes
      params.require(:paper_summary).permit *policy(@paper_summary || PaperSummary).permitted_attributes
    end
end

app/views/paper_summaries/_form.html.haml
= form_for @paper_summary, html: { class: 'form-horizontal', multipart: true } do |f|
  = render partial: 'shared/form_errors', locals: { resource: @paper_summary }

  %fieldset
    .form-group
      = f.label :title, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group
      = f.label :description, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_area :description, rows: 6, class: 'form-control'

    .form-group
      = f.label :trial_id, 'Trial', class: 'control-label col-sm-2'
      .col-sm-10
        = f.collection_select :trial_id, Trial.cached_all_for_select, :id, :display, {}, class: 'form-control'

    .form-group
      = f.label :species, 'Species', class: 'control-label col-sm-2'
      .col-sm-6
        = f.collection_select :species, PaperSummary::SPECIES, :to_s, :to_s, {}, class: 'form-control'

    .form-group
      = f.label :featured, 'Featured?', class: 'control-label col-sm-2'
      .col-sm-6
        .checkbox
          = f.check_box :featured, {}, 1, 0

    .form-group
      = f.label :document, class: 'control-label col-sm-2'
      .col-sm-10
        = f.file_field :document

    .form-group
      .col-sm-10.col-sm-offset-2
        = f.submit 'Save', class: 'btn btn-primary'

app/views/paper_summaries/_paper_summary.html.haml
.col-md-6
  .media.featured-research-box
    - if policy(paper_summary).download?
      = link_to download_paper_summary_path(paper_summary), class: 'pull-left', data: { 'no-turbolink' => true } do
        = file_type_icon paper_summary
    - else
      .pull-left
        = file_type_icon paper_summary
        
    .media-body
      %h3.media-heading= paper_summary.title
      %p.text-muted
        %i.paper-summary-description= paper_summary.description

      - if policy(paper_summary).download?
        = link_to download_paper_summary_path(paper_summary), class: 'btn btn-warning btn-download btn-xs', data: { 'no-turbolink' => true } do
          %i.fa.fa-cloud-download
          = p_space 'Download'

      .btn-group<
        - if policy(paper_summary).edit?
          = link_to edit_paper_summary_path(paper_summary), title: "Edit Summary", class: "btn btn-xs btn-warning" do
            %i.fa.fa-fw.fa-pencil
        - if policy(paper_summary).destroy?
          = link_to paper_summary, title: "Delete Summary", class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' }, method: :delete do
            %i.fa.fa-fw.fa-trash-o

app/views/paper_summaries/edit.html.haml
- title 'Paper Summary Uploader'

- breadcrumbs ['Paper Summaries', latest_research_path], ['Manage', manage_paper_summaries_path], 'Edit'

.row
  .col-md-12
    .box
      .box-header
        %h2
          %i.fa.fa-file-text
      .box-content
        = render 'form'

app/views/paper_summaries/index.html.haml
- title 'Latest Research', false


%h1
  %i.fa.fa-star.lightOrange
  = p_space "Latest Research"


- if @paper_summaries.any?
  %span#accordion
    - @paper_summaries.each do |species, summaries|
      %a{href: "#species-#{species.dasherize}", data: {toggle: "collapse", parent: "#accordion"}}
        %h3.species-header
          = species

      .panel-collapse.collapse.in{id: "species-#{species.dasherize}"}
        - summaries.in_groups_of(2).each do |summary_group|
          .row
            - summary_group.compact.each do |summary|
              = render summary
             
- else
  .row
    .col-md-12
      .alert.alert-info
        There are no featured research documents available yet. Come back soon!

%br/

- if policy(PaperSummary).create? || policy(PaperSummary).manage?
  .row
    .col-md-12.btn-row
      - if policy(PaperSummary).manage?
        = link_to manage_paper_summaries_path, class: 'btn btn-primary' do
          %i.fa.fa-cogs
          = p_space "Manage"
      - if policy(PaperSummary).create?
        = link_to new_paper_summary_path, class: 'btn btn-primary' do
          %i.fa.fa-plus
          = p_space "Upload New Summary"

app/views/paper_summaries/manage.html.haml
- title 'Latest Research Management'

- breadcrumbs ['Paper Summaries', latest_research_path], 'Manage'

%br/

.row
  .col-md-12
    %table.table.table-condensed.table-striped.repositionable-table
      %thead
        %tr
          %td.max-half Title
          %td.c Description
          %td.c Trial
          %td.c Level
          %td.c Species
          %td.c Position
          %td.c Featured?
          %td 

      %tbody
        - if @paper_summaries.any?
          - @paper_summaries.each do |paper_summary|
            %tr{data: {update_url: paper_summary_path(paper_summary), group: paper_summary.species, position: paper_summary.position}}
              %td.max-half= paper_summary.title
              %td.c
                %a.btn-link.description-popover{role: 'button', title: 'Description', data: {content: paper_summary.description}}
                  %i.fa.fa-ellipsis-h.fa-lg.fa-border
              %td.c= paper_summary.trial.complete_source_id
              %td.c= paper_summary.trial.display_level
              %td.c= paper_summary.species
              %td.c.position= paper_summary.position
              %td.c
                %i.fa{class: (paper_summary.featured ? 'fa-check text-success' : 'fa-times text-danger')}
              %td.c
                .btn-group<
                  - if policy(paper_summary).edit?
                    %a.btn.btn-xs.btn-info.inc-position-btn{title: 'Move Up', data: {'no-turbolink' => true}}
                      %i.fa.fa-fw.fa-chevron-up

                    %a.btn.btn-xs.btn-info.dec-position-btn{title: 'Move Down', data: {'no-turbolink' => true}}
                      %i.fa.fa-fw.fa-chevron-down

                    = link_to edit_paper_summary_path(paper_summary), title: "Edit Summary", class: "btn btn-xs btn-warning" do
                      %i.fa.fa-fw.fa-pencil
                  - if policy(paper_summary).destroy?
                    = link_to paper_summary, title: "Delete Summary", class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' }, method: :delete do
                      %i.fa.fa-fw.fa-trash-o

%br/

.row
  .col-md-12
    = link_to new_paper_summary_path, class: 'btn btn-primary' do
      %i.fa.fa-plus
      = p_space "Upload New Summary"

app/views/paper_summaries/new.html.haml
- title 'Paper Summary Uploader'

- breadcrumbs ['Paper Summaries', latest_research_path], ['Manage', manage_paper_summaries_path], 'New'

.row
  .col-md-12
    .box
      .box-header
        %h2
          %i.fa.fa-file-text
      .box-content
        = render 'form'