config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'pages#welcome', as: :welcome

  resource :feedback, only: [:new, :create]
  resources :access_requests, only: [:new, :create]

  resources :users, except: :show do
    member do
      post 'invite', to: 'invites#create', as: :invite
      get 'register/:invite_token', to: 'invites#edit', as: :rsvp
      match 'register', to: 'invites#update', via: [:patch, :put], as: :register
    end
  end

  resources :papers, except: :index do
    root to: 'trials#index'
    get 'download', on: :member, as: :download
    collection do
      get 'lookup', to: 'paper_searches#lookup', as: :lookup
      get 'search', to: 'paper_searches#search', as: :search
    end
    resources :trials
    resources :supplementals, except: [:index, :show], id: /[A-Za-z0-9\.]+?/, format: /html|js|json/
  end

  resources :supplementals, except: :show, id: /[A-Za-z0-9\.]+?/, format: /html|js|json/ do
    get 'download', on: :member, as: :download
  end

  resources :paper_summaries do
    get 'download', on: :member, as: :download
    collection do
      get 'manage', to: 'paper_summaries#manage', as: :manage
    end
  end
  get 'latest', to: 'paper_summaries#index', as: :latest_research

  resources :trials, only: :index
  resources :measures, only: [:new, :create, :edit, :update, :destroy], as: :performance_measures

  resources :sales_aids do
    get 'download', on: :member, as: :download
    collection do
      get 'manage', to: 'sales_aids#manage', as: :manage
    end
  end
  get 'learn-more', to: 'sales_aids#index', as: :learn_more

  resources :sessions, only: [:new, :create, :destroy]
  resource :password_reset, only: [:new, :create, :edit, :update]
  resource :role_impersonation, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  root to: 'pages#welcome'
end

app/models/sales_aid.rb
class SalesAid < ActiveRecord::Base
  belongs_to :user

  CATEGORIES = {presentation: :document, literature: :document, document: :document, calculator: :link, newsletter: :document, video: :video}
  ACCESS_LEVELS = {guest: 0, public_sales: 1, biozyme: 2, _private: 3}

  include FileDataManagement

  enum access_level: ACCESS_LEVELS
  store :video_data, accessors: [:name, :summary, :thumbnail_url, :large_thumbnail_url]
  mount_uploader :document, SalesAidUploader
  acts_as_list scope: [:category]

  validates :title,        presence: true
  validates :category,     presence: true,
                           inclusion: { in: CATEGORIES.keys.map(&:to_s) }
  validates :user_id,      presence: true
  validates :access_level, presence: true
  validates :document,     presence: { if: lambda { |s| type == :document } }
  validates :video_id,     presence: { if: lambda { |s| s.video? } }
  validates :link,         presence: { if: lambda { |s| s.external_link? } },
                           format: {
                            with: /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\z/ix,
                            allow_nil: true,
                            if: lambda { |s| s.external_link? }
                           }

  scope :for_country, -> (country) { where("?::text = ANY (country_codes)", country) if country.present? }
  scope :with_country_names, -> { select("ARRAY(SELECT name FROM countries WHERE countries.country_code = ANY (sales_aids.country_codes)) AS country_names") }

  before_save :set_video_metadata, :normalize_country_codes
  after_commit :flush_cache

  def self.countries
    Country.where(country_code: pluck(:country_codes).flatten.uniq).order(name: :asc).to_a
  end

  def self.cached_countries
    Rails.cache.fetch([name, 'countries']){ countries }
  end

  def type
    CATEGORIES.with_indifferent_access[category]
  end

  def external_link?
    type == :link
  end

  def video?
    type == :video
  end

  def get_video
    Yt::Video.new id: video_id
  rescue
    nil
  end

  def countries
    Rails.cache.fetch([self, 'countries']){ Array(country_codes).any? ? Country.where(country_code: country_codes).to_a : [] }
  end

  private

  def set_video_metadata
    if video? && v = get_video
      self.name = v.title
      self.summary = v.description
      self.thumbnail_url = v.thumbnail_url
      self.large_thumbnail_url = v.thumbnail_url
    end
  rescue => e
    ExceptionNotifier.notify_exception e, data: { video_id: id, youtube_id: video_id }
  end

  def normalize_country_codes
    self.country_codes = Array(country_codes).reject(&:blank?).uniq
  end

  def flush_cache
    Rails.cache.delete([self.class.name, 'countries'])
  end
end

app/controllers/sales_aids_controller.rb
class SalesAidsController < ApplicationController
  before_action :set_sales_aid, only: [:show, :edit, :update, :destroy, :download]

  def index
    authorize! SalesAid
    @sales_aids = (policy_scope SalesAid.order(:category, :position)).all.group_by(&:category)
  end

  def show
    respond_with_js do
      render :nothing unless @sales_aid.video?
    end
  end

  def new
    @sales_aid = SalesAid.new
    authorize! @sales_aid
  end

  def edit
  end

  def create
    @sales_aid = current_user.sales_aids.build(sales_aid_attributes)
    authorize! @sales_aid

    if @sales_aid.save
      redirect_to manage_sales_aids_path, notice: 'Sales aid was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    respond_to do |format|
      format.html {
        if @sales_aid.update(sales_aid_attributes)
          redirect_to manage_sales_aids_path, notice: 'Sales Aid was successfully updated.'
        else
          render action: 'edit'
        end
      }
      format.json {
        new_position = params[:reposition].try(:to_i)
        if new_position && @sales_aid.insert_at(new_position)
          render json: @sales_aid, status: :created, location: @sales_aid
        else
          render json: @sales_aid.errors, status: :unprocessable_entity
        end
      }
    end
  end

  def destroy
    @sales_aid.destroy
    redirect_to manage_sales_aids_path
  end

  def manage
    @sales_aids = policy_scope(SalesAid).order(:category, :position)
    authorize! @sales_aids
  end

  def download
    send_data (open @sales_aid.document.url).read,
      type: @sales_aid.document.file.content_type,
      filename: @sales_aid.filename,
      disposition: 'attachment'
  end

  private
    def set_sales_aid
      @sales_aid = SalesAid.find(params[:id])
      authorize! @sales_aid
    end

    def sales_aid_attributes
      params.require(:sales_aid).permit *policy(@sales_aid || SalesAid).permitted_attributes
    end
end

app/helpers/sales_aids_helper.rb
module SalesAidsHelper
  def file_type_icon(sales_aid)
    icon = case sales_aid.file_extension
      when :pdf then 'fa-file-pdf-o'
      when :doc, :docx then 'fa-file-word-o'
      when :ppt, :pptx then 'fa-file-powerpoint-o'
      when :xls, :xlsx then 'fa-file-excel-o'
      else 'fa-file'
      end

    content_tag :i, nil, class: "media-object burntOrange fa fa-3x #{icon}"
  end

  def sales_aid_category_icon(category)
    icon = case category.to_sym
      when :calculator then 'fa-sliders'
      when :video then 'fa-youtube-play'
      else 'fa-files-o'
      end
      
    content_tag :i, nil, class: "fa #{icon}"
  end

  def sales_aid_category(category, options = {})
    display = options.fetch(:plural, false) ? category.pluralize : category 
    display.titleize
      .sub('Newsletter', 'eNewsletter')
      .sub('Documents', 'Specs & Certificates')
      .sub('Document', 'Spec/Certificate')
  end
end

app/views/sales_aids/_form.html.haml
= form_for @sales_aid, html: { class: 'form-horizontal', multipart: true } do |f|
  = render partial: 'shared/form_errors', locals: { resource: @sales_aid }

  %fieldset
    .form-group
      = f.label :title, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group
      = f.label :category, 'Literature Type', class: 'control-label col-sm-2'
      .col-sm-6
        = f.collection_select :category, SalesAid::CATEGORIES.keys.map(&:to_s), :to_s, Proc.new{|c| sales_aid_category c }, {}, class: 'form-control category-select'

    .form-group
      = f.label :access_level, class: 'control-label col-sm-2'
      .col-sm-6
        = f.collection_select :access_level, policy(SalesAid).accessible_levels.keys.map(&:to_s), :to_s, :humanize, {}, class: 'form-control'

    .form-group
      = f.label :country_codes, 'Countries', class: 'control-label col-sm-2'
      .col-sm-6
        = f.select :country_codes, grouped_options_for_select(Country.grouped_options, f.object.country_codes), { include_hidden: true }, multiple: true, size: 10, class: 'form-control'

    .form-group.document-type
      = f.label :document, class: 'control-label col-sm-2'
      .col-sm-10
        = f.file_field :document

    .form-group.video-type
      = f.label :video_id, 'YouTube ID', class: 'control-label col-sm-2'
      .col-sm-10
        .input-group
          %span.input-group-addon= 'http://youtube.com/watch?v='
          = f.text_field :video_id, class: 'form-control'

    .form-group.calculator-type
      = f.label :link, 'URL', class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :link, class: 'form-control'

    .form-group
      .col-sm-10.col-sm-offset-2
        = f.submit 'Save', class: 'btn btn-primary'

app/views/sales_aids/_sales_aid.html.haml
- if sales_aid.video?
  .col-md-3.col-sm-6
    = link_to sales_aid, remote: true, class: 'thumbnail sales-aid-thumbnail' do
      = image_tag sales_aid.large_thumbnail_url, class: 'img-responsive'
      .caption
        %h2= sales_aid.title

- elsif sales_aid.external_link?
  .col-md-3.col-sm-6
    = link_to sales_aid.link, target: :_blank, class: 'quick-button' do
      %i.fa.fa-calculator.burntOrange
      %p= sales_aid.title
    %br.hidden-xs/

- else
  .col-md-4
    .media.sales-aid
      = link_to download_sales_aid_path(sales_aid), class: 'pull-left', data: { 'no-turbolink' => true } do
        = file_type_icon sales_aid
      .media-body
        %h2.media-heading= sales_aid.title
        = link_to download_sales_aid_path(sales_aid), class: 'btn btn-info btn-xs', data: { 'no-turbolink' => true } do
          %i.fa.fa-cloud-download
          = p_space 'Download'

app/views/sales_aids/_video_modal.html.haml
.modal.fade{id: "sales-aid-video-modal", role: 'dialog', aria: {labelledby: "sales-aid-video-modal-label", hidden: 'true'}}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: 'button', data: {dismiss: 'modal'}, aria: {hidden: 'true'}} &times;
        %h3.modal-title{id: "sales-aid-video-modal-label"}= sales_aid.title

      - if video = sales_aid.get_video
        .modal-body.video
          .embed-responsive.embed-responsive-16by9
            != video.embed_html5({id: 'sales-aid-video-embed', fullscreen: true, url_params: { showinfo: 0, enablejsapi: 1}})

      - else
        .modal-body
          .alert.alert-warning
            %i.fa.fa-exclamation-triangle
            = p_space 'Video Not Available'

app/views/sales_aids/edit.html.haml
- title 'Sales Aid Uploader'

- breadcrumbs ['Learn More', sales_aids_path], 'Edit'

.row
  .col-md-12
    .box
      .box-header
        %h2
          %i.fa.fa-file-text
      .box-content
        = render 'form'

app/views/sales_aids/index.html.haml
- title 'Learn More'

%br/

- if @sales_aids.any?
  - @sales_aids.each do |category, sales_aids|
    .row
      .col-md-12
        .panel.panel-primary
          .panel-heading
            %h3.panel-title
              = sales_aid_category_icon category
              = p_space sales_aid_category(category, plural: true)

          .panel-body
            - sales_aids.in_groups_of(category.in?(%w[video calculator]) ? 4 : 3).each do |grouped_sales_aids|
              .row.sales-aid-row
                - grouped_sales_aids.compact.each do |sales_aid|
                  = render sales_aid

- else
  .row
    .col-md-12
      .alert.alert-info
        There are no documents available yet. Come back soon!

%br/

- if policy(SalesAid).create? || policy(SalesAid).manage?
  .row
    .col-md-12.btn-row
      - if policy(SalesAid).manage?
        = link_to manage_sales_aids_path, class: 'btn btn-primary' do
          %i.fa.fa-cogs
          = p_space "Manage"

      - if policy(SalesAid).create?
        = link_to new_sales_aid_path, class: 'btn btn-primary' do
          %i.fa.fa-plus
          = p_space "Upload New Sales Aid"

app/views/sales_aids/manage.html.haml
- title 'Sales Aid Management'

- breadcrumbs ['Learn More', learn_more_path], 'Manage'

%br/

.row
  .col-md-12
    %table.table.table-condensed.table-striped.repositionable-table
      %thead
        %tr
          %td.max-half Title
          %td.c Category
          %td.c Countries
          %td.c Position
          %td.c Access Level
          %td

      %tbody
        - if @sales_aids.any?
          - @sales_aids.each do |sales_aid|
            %tr{data: {update_url: sales_aid_path(sales_aid), group: sales_aid.category, position: sales_aid.position}}
              %td.max-half= sales_aid.title
              %td.c= sales_aid_category sales_aid.category
              %td.c= sales_aid.country_codes.join ' / '
              %td.c.position= sales_aid.position
              %td.c= sales_aid.access_level.titleize
              %td.c
                .btn-group<
                  - if policy(sales_aid).edit?
                    %a.btn.btn-xs.btn-info.inc-position-btn{title: 'Move Up', data: {'no-turbolink' => true}}
                      %i.fa.fa-fw.fa-chevron-up

                    %a.btn.btn-xs.btn-info.dec-position-btn{title: 'Move Down', data: {'no-turbolink' => true}}
                      %i.fa.fa-fw.fa-chevron-down

                    = link_to edit_sales_aid_path(sales_aid), title: "Edit Sales Aid", class: "btn btn-xs btn-warning" do
                      %i.fa.fa-fw.fa-pencil
                  - if policy(sales_aid).destroy?
                    = link_to sales_aid, title: "Delete Sales Aid", class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' }, method: :delete do
                      %i.fa.fa-fw.fa-trash-o

%br/

.row
  .col-md-12
    = link_to new_sales_aid_path, class: 'btn btn-primary' do
      %i.fa.fa-plus
      = p_space "Upload New Sales Aid"

app/views/sales_aids/new.html.haml
- title 'Sales Aid Uploader'

- breadcrumbs ['Learn More', sales_aids_path], 'New'

.row
  .col-md-12
    .box
      .box-header
        %h2
          %i.fa.fa-file-text
      .box-content
        = render 'form'