config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'pages#welcome', as: :welcome

  resource :feedback, only: [:new, :create]
  resources :access_requests, only: [:new, :create]

  resources :users, except: :show do
    member do
      post 'invite', to: 'invites#create', as: :invite
      get 'register/:invite_token', to: 'invites#edit', as: :rsvp
      match 'register', to: 'invites#update', via: [:patch, :put], as: :register
    end
  end

  resources :papers, except: :index do
    root to: 'trials#index'
    get 'download', on: :member, as: :download
    collection do
      get 'lookup', to: 'paper_searches#lookup', as: :lookup
      get 'search', to: 'paper_searches#search', as: :search
    end
    resources :trials
    resources :supplementals, except: [:index, :show], id: /[A-Za-z0-9\.]+?/, format: /html|js|json/
  end

  resources :supplementals, except: :show, id: /[A-Za-z0-9\.]+?/, format: /html|js|json/ do
    get 'download', on: :member, as: :download
  end

  resources :paper_summaries do
    get 'download', on: :member, as: :download
    collection do
      get 'manage', to: 'paper_summaries#manage', as: :manage
    end
  end
  get 'latest', to: 'paper_summaries#index', as: :latest_research

  resources :trials, only: :index
  resources :measures, only: [:new, :create, :edit, :update, :destroy], as: :performance_measures

  resources :sales_aids do
    get 'download', on: :member, as: :download
    collection do
      get 'manage', to: 'sales_aids#manage', as: :manage
    end
  end
  get 'learn-more', to: 'sales_aids#index', as: :learn_more

  resources :sessions, only: [:new, :create, :destroy]
  resource :password_reset, only: [:new, :create, :edit, :update]
  resource :role_impersonation, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  root to: 'pages#welcome'
end

app/models/trial.rb
class Trial < ActiveRecord::Base
  belongs_to :paper
  has_many :performance_measures, dependent: :destroy
  has_many :paper_summaries, dependent: :destroy

  include Filterable

  LEVELS = {web: 0, shared: 2, biozyme: 1, _private: 3}
  enum level: LEVELS

  validates :source_sub_id, presence: true,
                            uniqueness: { scope: :paper_id, case_sensitive: false },
                            format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :year, presence: true
  validates :level, presence: true
  acts_as_taggable_on :species, :focus

  after_initialize :set_default_source_sub_id
  after_commit :flush_cache

  delegate :source_id, :title, :citation, :formatted_citation, :location, :literature_type, :product, :journal, :document, :author_name, to: :paper
  attr_accessor :calculation_list
  accepts_nested_attributes_for :performance_measures

  def self.find(input)
    input.to_i == 0 ? where(source_sub_id: input).first : super
  end

  def self.display_level(level)
    level.sub('web', 'public').titleize.sub('Biozyme', 'BioZyme')
  end

  def self.cached_species
    Rails.cache.fetch([name, 'species']) do
      ActsAsTaggableOn::Tagging.joins(:tag).where(context: 'species').pluck(:name).uniq.sort
    end
  end

  def self.cached_species_for(user)
    Rails.cache.fetch([name, 'species', user.current_role]) do
      TrialPolicy::Scope.new(user, Trial).resolve.to_a.map{|t| t.cached_species_list }.flatten.uniq.sort
    end
  end

  def self.cached_focuses
    Rails.cache.fetch([name, 'focuses']) do
      ActsAsTaggableOn::Tagging.joins(:tag).where(context: 'focus').pluck(:name).uniq.sort
    end
  end

  def self.cached_focuses_for(user)
    Rails.cache.fetch([name, 'focuses', user.current_role]) do
      TrialPolicy::Scope.new(user, Trial).resolve.to_a.map{|t| t.cached_focus_list }.flatten.uniq.sort
    end
  end

  def self.cached_years
    Rails.cache.fetch([name, 'years']){ pluck(:year).uniq.sort }
  end

  def self.cached_years_for(user)
    Rails.cache.fetch([name, 'years', user.current_role]){ TrialPolicy::Scope.new(user, Trial).resolve.pluck(:year).uniq.sort }
  end

  def self.cached_calculations
    Rails.cache.fetch([name, 'calculations']){ pluck(:calculations).flatten.uniq.sort }
  end

  def self.cached_all_for_select
    Rails.cache.fetch [self, 'all-for-select'] do
      Struct.new 'TrialForSelect', :id, :display
      includes(:paper).order(:paper_id, :source_sub_id).to_a.map do |t|
        Struct::TrialForSelect.new t.id, [t.complete_source_id, t.paper.title.truncate(80, separator: ' ')].join(' - ')
      end
    end
  end

  def self.expand_species_list(list)
    list = Array(list)
    list += ['Ruminant'] if (list & ['Beef', 'Dairy', 'Sheep', 'Goat']).any?
    list.uniq
  end

  def cached_species_list
    Rails.cache.fetch([self, 'species-list']){ species_list }
  end

  def cached_focus_list
    Rails.cache.fetch([self, 'focus-list']){ focus_list }
  end

  scope :with_paper_and_author, -> { joins(paper: :author) }
  scope :for_species,     -> (species) {
    species = Trial.expand_species_list(species)
    species.count > 1 ? for_any_species(species) : tagged_with(species, on: :species)
  }
  scope :for_any_species, -> (species) { tagged_with(Trial.expand_species_list(species), on: :species, any: 'distinct') }
  scope :for_focus,       -> (focus)   { tagged_with(focus, on: :focus) }
  scope :for_any_focus,   -> (focus)   { tagged_with(focus, on: :focus, any: 'distinct') }
  scope :for_author,      -> (author)  { where authors: { id: author } }
  scope :for_journal,     -> (journal) { where papers: { journal: journal } }

  def to_param
    source_sub_id
  end

  def complete_source_id
    [source_id, source_sub_id].join '-'
  end

  def calculation_list
    calculations.join ', '
  end

  def calculation_list=(list)
    list ||= []
    self.calculations = list.is_a?(String) ? list.split(',').map(&:strip) : list
  end

  def expanded_species_list
    cached_species_list.to_s.gsub(/ruminant/i, 'Beef, Dairy, Sheep, Goat')
  end

  def display_level
    self.class.display_level level
  end

  private

  def flush_cache
    Rails.cache.delete([self.class.name, 'years'])
    Rails.cache.delete([self.class.name, 'species'])
    Rails.cache.delete([self.class.name, 'focuses'])
    Rails.cache.delete([self.class.name, 'calculations'])
    Rails.cache.delete([self.class.name, 'all-for-select'])
    Rails.cache.delete([self, 'species-list'])
    Rails.cache.delete([self, 'focus-list'])
    User.roles.values.each do |role|
      Rails.cache.delete([self.class.name, 'years', role])
      Rails.cache.delete([self.class.name, 'species', role])
      Rails.cache.delete([self.class.name, 'focuses', role])
    end
  end

  def set_default_source_sub_id
    self.source_sub_id ||= Trial.where(paper_id: paper_id).maximum(:source_sub_id).try(:succ) || 'A'
  end
end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  before_action :set_paper, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_trial, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html {
        redirect_to paper_path(params[:paper_id]) if params[:paper_id]
      }
      format.js {
        scope_trials
        @trials = @trials.page(params[:page]).per_page(15)
      }
      format.xls {
        scope_trials
        headers["Content-Disposition"] = "attachment; filename=\"Research Center Table.xls\""
      }
    end
  end

  def show
    render 'papers/show'
  end

  def new
    @trial = @paper.trials.build
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @trial = @paper.trials.build trial_attributes

    respond_to do |format|
      if @trial.save
        format.html { redirect_to @paper, notice: 'Trial was successfully created.' }
        format.js
      else
        format.html { render action: 'new' }
        format.js { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @trial.update(trial_attributes)
        format.html { redirect_to @paper, notice: 'Trial was successfully updated.' }
        format.js
      else
        format.html { render action: 'edit' }
        format.js { render action: 'edit' }
      end
    end
  end

  def destroy
    @trial.destroy
    respond_to do |format|
      format.html { redirect_to @paper }
      format.js
    end
  end

  private
    def set_paper
      @paper = Paper.find params[:paper_id] if params[:paper_id]
    end

    def set_trial
      @trial = current_resource
      authorize! @trial
    end

    def current_resource
      if params[:action] == 'create'
        @current_resource ||= params[:trial] if params[:trial]
      else
        @current_resource ||= @paper.trials.where(source_sub_id: params[:id]).first if params[:id]
      end
    end

    def trial_attributes
      params.require(:trial).permit *policy(@trial || Trial).permitted_attributes
    end

    def scope_trials
      @trials = Trial.filter(params.slice(:species, :focus, :author, :journal), :with_paper_and_author)
      @trials = policy_scope @trials.order("#{sort_column} #{sort_direction}").order('year asc')
    end

    def sort_column
      super(Trial.column_names + ['papers.title', 'papers.journal'], 'year')
    end

    def sort_direction(default = 'desc')
      super(default)
    end
end

app/helpers/trials_helper.rb
module TrialsHelper
  def display_percentage(value)
    value.blank? ? '' : "#{value}%"
  end
end

app/views/trials/_form.html.haml
= form_for [trial.paper, trial], remote: defined?(remote), html: { class: 'form-horizontal' } do |f|
  = render partial: 'shared/form_errors', locals: { resource: trial }

  %fieldset
    .container
      .row
        .col-md-6
          .form-group
            = f.label :source_sub_id, 'Trial Letter', class: 'control-label col-sm-2 col-md-4'
            .col-sm-10.col-md-8
              .input-group
                %span.input-group-addon= "#{trial.paper_id}-"
                = f.text_field :source_sub_id, class: 'form-control'

        .col-md-6
          .form-group
            = f.label :level, class: 'control-label col-sm-2 col-md-4'
            .col-sm-10.col-md-8
              - f.object.level = nil if f.object.new_record? && f.object.errors.none?
              = f.collection_select :level, policy(Trial).accessible_levels.keys.map(&:to_s), :to_s, Proc.new{|l| Trial.display_level(l) }, {include_blank: 'Choose...'}, class: 'form-control'

      .row
        .col-md-12
          .form-group
            = f.label :summary, class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_area :summary, class: 'form-control'

      .row
        .col-md-6
          .form-group
            = f.label :year, class: 'control-label col-sm-2 col-md-4'
            .col-sm-10.col-md-8
              = f.text_field :year, class: 'form-control'

        .col-md-6
          .form-group
            = f.label :species_list, 'Species', class: 'control-label col-sm-2 col-md-4'
            .col-sm-10.col-md-8
              = f.text_field :species_list, class: 'form-control species-select2', value: f.object.species_list.to_s, data: { tags: Trial.cached_species }
              %span.help-block Separate with commas

      .row
        .col-md-12
          .form-group
            = f.label :focus_list, 'Focus(es)', class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_field :focus_list, class: 'form-control focuses-select2', value: f.object.focus_list.to_s, data: { tags: Trial.cached_focuses }
              %span.help-block Separate with commas

      .row
        .col-md-12
          .form-group
            = f.label :calculation_list, 'Included in X Calculations', class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_field :calculation_list, class: 'form-control calculations-select2', value: f.object.calculation_list.to_s, data: { tags: Trial.cached_calculations }
              %span.help-block Separate with commas

      .row
        .col-md-4
          .form-group
            = f.label :dose, class: 'control-label col-md-6 col-sm-2'
            .col-md-5.col-sm-10
              = f.text_field :dose, class: 'form-control'

        .col-md-4
          .form-group
            = f.label :forage, 'Forage', class: 'control-label col-md-6 col-sm-2'
            .col-md-6.col-sm-10
              = f.text_field :forage, class: 'form-control'

        .col-md-4
          .form-group
            = f.label :concentrate, 'Concentrate', class: 'control-label col-md-6 col-sm-2'
            .col-md-6.col-sm-10
              = f.text_field :concentrate, class: 'form-control'

      .row
        .col-md-12
          .form-group
            .col-sm-offset-2.col-sm-10
              %hr/
              = f.submit class: 'btn btn-primary'
              = f.submit 'Create and Add Another', class: 'btn btn-primary' if @trial.new_record? && !defined?(remote)
              = link_to 'Cancel', papers_path, class: 'btn btn-inverse cancel-btn'

app/views/trials/_new_trial_box.html.haml
.box.new-trial-box
  .box-header
    %h2
      %i.fa.fa-flask
      New Trial

  .box-content
    %span.trial-box-edit
      = render partial: 'trials/form', locals: { trial: trial, remote: true }

app/views/trials/_new_trial_box_row.html.haml
.row
  .col-md-12
    = render partial: 'new_trial_box', locals: { trial: trial }

app/views/trials/_trial.html.haml
%tr
  %td{style: 'width: 20%;', rowspan: 2}
    = a_space trial.title
    %a.btn-link.reference-popover{role: 'button', title: 'Reference', data: {content: trial.formatted_citation}}
      = "..."
  - if current_user >= :manager
    %td.c{rowspan: 2}= trial.complete_source_id
  %td.c{rowspan: 2}= trial.author_name
  %td.c{rowspan: 2}= trial.year
  %td.c{rowspan: (trial.journal ? 1 : 2)}= trial.literature_type
  %td.c{rowspan: 2}= trial.expanded_species_list.gsub(', ', '<br/>').html_safe
  %td.c{rowspan: 2}= trial.cached_focus_list.join('<br/>').html_safe
  %td.c{rowspan: 2}= trial.dose
  %td.c{rowspan: 2}
    %a.btn-link.summary-popover{role: 'button', title: 'Summary', data: {content: trial.summary}}
      %i.fa.fa-ellipsis-h.fa-lg.fa-border
  %td.c{rowspan: 2}
    .btn-group.btn-group-vertical<
      = link_to [trial.paper, trial], title: 'View', class: 'btn btn-xs btn-secondary' do
        %i.fa.fa-fw.fa-eye
      - if policy(trial).edit?
        = link_to edit_paper_trial_path(trial.paper, trial), title: "Edit Trial", class: "btn btn-xs btn-warning" do
          %i.fa.fa-fw.fa-pencil
      - if policy(trial).destroy?
        = link_to [trial.paper, trial], title: "Delete Trial", class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' }, method: :delete do
          %i.fa.fa-fw.fa-trash-o
%tr
  - if trial.journal
    %td.c= trial.journal

app/views/trials/_trials.html.haml
.table-responsive
  %table.table.table-condensed.table-bordered#trials-table
    %thead
      - if trials.any?
        %tr
          %th{style: 'width: 20%;', rowspan: 2}= sortable 'papers.title', 'Title'
          - if current_user >= :manager
            %th.c{rowspan: 2}= sortable :paper_id, 'Source'
          %th.c{rowspan: 2} Author
          %th.c{rowspan: 2}= sortable :year
          %th.c= sortable :literature_type, 'Literature Type'
          %th.c{rowspan: 2} Species
          %th.c{rowspan: 2} Focus
          %th.c{rowspan: 2} Dose
          %th.c{rowspan: 2} Summary
          %th.c{rowspan: 2}
        %tr
          %th.c= sortable 'papers.journal', 'Journal'

    %tbody
      - if trials.any?
        = render trials
      - else
        %tr.warning
          %td.c{colspan: 9}
            %br/
            There are no trials that match the current filters.
            %br/
            %br/

  .text-center
    = will_paginate trials

app/views/trials/edit.html.haml
- title "Edit Trial", false

- breadcrumbs ['Literature', papers_path], [@trial.paper.source_id, paper_path(@trial.paper)], ["Trial #{@trial.source_sub_id}", paper_trial_path(@trial.paper, @trial)], 'Edit'

%h1
  Edit Trial
  %br/
  %small= @trial.title

.row
  .col-md-12
    .box
      .box-header
        %h2
          %i.fa.fa-flask
      .box-content
        = render partial: 'form', locals: { trial: @trial }

%h1 Performance Measures

.row#performance-measures-row
  - @trial.performance_measures.each do |measure|
    = render partial: 'measures/measure', locals: { measure: measure, editable: true }

  .col-md-3.col-xs-6.col-xxs-12.new-performance-measure-btn-container
    = link_to new_performance_measure_path(trial: @trial.id), remote: true, class: 'quick-button' do
      %i.fa.fa-plus
      %p New

app/views/trials/index.html.haml
- title 'Trials', false

.row
  .col-md-4.col-md-offset-8
    = form_tag lookup_papers_path, method: :get, remote: true, class: 'form-inline inline-block' do
      .form-group
        .input-group.input-group-sm
          = text_field_tag :q, '', placeholder: 'Paper/Trial Number', class: 'form-control'
          %span.input-group-btn
            = submit_tag 'Go', class: 'btn btn-sm btn-primary'

%br/

.row
  .col-md-12
    .box.full-color
      .box-content
        = form_tag trials_path, method: :get, id: 'trial_filter' do
          .row
            .col-md-3.text-center
              %h4.white Species
              = select_tag :species, options_for_select(Trial.cached_species_for(current_user), params[:species]), include_blank: true, class: 'form-control'

            .col-md-3.text-center
              %h4.white Focus
              = select_tag :focus, options_for_select(Trial.cached_focuses_for(current_user), params[:focus]), include_blank: true, class: 'form-control'

            .col-md-3.text-center
              %h4.white Author
              = select_tag :author, options_from_collection_for_select(Author.cached_having_papers(current_user), :id, :last_name, params[:author]), include_blank: true, class: 'form-control'

            .col-md-3.text-center
              %h4.white Peer Reviewed
              = select_tag :journal, options_for_select(Paper.cached_journals_for(current_user), params[:journal]), include_blank: true, class: 'form-control'

.row
  .col-md-12#trials-container{data: {url: trials_path(params.slice(:species, :focus, :author, :journal, :sort, :direction, :page))}}
    %h2.text-center.text-info
      %i.fa.fa-spinner.fa-spin
      = p_space 'Loading'

%br/

- if policy(Trial).create?
  .row
    .col-md-12.btn-row
      = link_to trials_path(params.slice(:species, :focus, :author, :journal, :sort, :direction).merge(format: :xls)), class: 'btn btn-success', target: :_blank do
        %i.fa.fa-floppy-o
        = p_space "Export"

      = link_to new_paper_path, class: 'btn btn-primary' do
        %i.fa.fa-plus
        = p_space "Add Literature"

app/views/trials/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">
    <WindowHeight>12220</WindowHeight>
    <WindowWidth>19220</WindowWidth>
    <WindowTopX>120</WindowTopX>
    <WindowTopY>140</WindowTopY>
    <ProtectStructure>False</ProtectStructure>
    <ProtectWindows>False</ProtectWindows>
   </ExcelWorkbook>
  <Styles>
    <Style ss:ID="Default" ss:Name="Normal">
     <Alignment ss:Vertical="Bottom"/>
     <Borders/>
     <Interior/>
     <NumberFormat/>
     <Protection/>
    </Style>
    <Style ss:ID="s62">
     <Alignment ss:Horizontal="Center" ss:Vertical="Bottom"/>
    </Style>
    <Style ss:ID="s63">
     <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
    </Style>
    <Style ss:ID="s64">
     <Alignment ss:Horizontal="Center" ss:Vertical="Bottom" ss:WrapText="1"/>
    </Style>
    <Style ss:ID="s65">
     <Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/>
    </Style>
  </Styles>
  <Worksheet ss:Name="Sheet1">
    <Table ss:StyleID="s62" ss:DefaultColumnWidth="65" ss:DefaultRowHeight="15">
      <Column ss:Index="2" ss:StyleID="s64" ss:AutoFitWidth="0" ss:Width="290"/>
      <Row ss:AutoFitHeight="0" ss:Height="72" ss:StyleID="s63">
        <Cell><Data ss:Type="String">Source #</Data></Cell>
        <Cell ss:StyleID="s65"><Data ss:Type="String">Title</Data></Cell>
        <Cell><Data ss:Type="String">Year</Data></Cell>
        <Cell><Data ss:Type="String">Author</Data></Cell>
        <Cell><Data ss:Type="String">Location</Data></Cell>
        <Cell><Data ss:Type="String">Literature Type</Data></Cell>
        <Cell><Data ss:Type="String">Species</Data></Cell>
        <Cell><Data ss:Type="String">Focus</Data></Cell>
        <Cell><Data ss:Type="String">Dose</Data></Cell>
      </Row>
    <% @trials.includes(paper: :author).each do |trial| %>
      <Row ss:AutoFitHeight="0" ss:Height="72" ss:StyleID="s63">
        <Cell><Data ss:Type="String"><%= trial.complete_source_id %></Data></Cell>
        <Cell ss:StyleID="s65"><Data ss:Type="String"><%= trial.title %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= trial.year %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trial.author_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trial.location %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trial.literature_type %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trial.expanded_species_list.gsub(', ', '; ') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trial.cached_focus_list.join('; ') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= trial.dose %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>