config/routes.rb
Rails.application.routes.draw do
  get 'welcome', to: 'pages#welcome', as: :welcome

  resource :feedback, only: [:new, :create]
  resources :access_requests, only: [:new, :create]

  resources :users, except: :show do
    member do
      post 'invite', to: 'invites#create', as: :invite
      get 'register/:invite_token', to: 'invites#edit', as: :rsvp
      match 'register', to: 'invites#update', via: [:patch, :put], as: :register
    end
  end

  resources :papers, except: :index do
    root to: 'trials#index'
    get 'download', on: :member, as: :download
    collection do
      get 'lookup', to: 'paper_searches#lookup', as: :lookup
      get 'search', to: 'paper_searches#search', as: :search
    end
    resources :trials
    resources :supplementals, except: [:index, :show], id: /[A-Za-z0-9\.]+?/, format: /html|js|json/
  end

  resources :supplementals, except: :show, id: /[A-Za-z0-9\.]+?/, format: /html|js|json/ do
    get 'download', on: :member, as: :download
  end

  resources :paper_summaries do
    get 'download', on: :member, as: :download
    collection do
      get 'manage', to: 'paper_summaries#manage', as: :manage
    end
  end
  get 'latest', to: 'paper_summaries#index', as: :latest_research

  resources :trials, only: :index
  resources :measures, only: [:new, :create, :edit, :update, :destroy], as: :performance_measures

  resources :sales_aids do
    get 'download', on: :member, as: :download
    collection do
      get 'manage', to: 'sales_aids#manage', as: :manage
    end
  end
  get 'learn-more', to: 'sales_aids#index', as: :learn_more

  resources :sessions, only: [:new, :create, :destroy]
  resource :password_reset, only: [:new, :create, :edit, :update]
  resource :role_impersonation, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout

  root to: 'pages#welcome'
end

app/models/paper.rb
class Paper < ActiveRecord::Base
  self.primary_key = :source_id

  belongs_to :author
  has_many :trials, dependent: :destroy
  has_many :supplementals, dependent: :destroy

  include Filterable
  include FileDataManagement

  PRODUCTS = ['AMAFERM', 'AO-Biotics']
  LITERATURE_TYPES = [
    "Abstract",
    "Book",
    "Controlled Field Trial",
    "Dissertation",
    "Final Report",
    "Journal Article",
    "Proceedings & Bulletins",
    "Thesis"
  ]

  mount_uploader :document, DocumentUploader

  attr_accessor :author_name
  accepts_nested_attributes_for :trials

  validates :author_id, presence: true
  validates :citation, presence: true

  validates :literature_type, inclusion: { in: LITERATURE_TYPES }
  validates :product, presence: true, inclusion: { in: PRODUCTS }

  before_save :normalize_values
  after_commit :flush_cache

  def self.cached_journals
    Rails.cache.fetch([name, 'journals']){ pluck(:journal).uniq.compact.sort }
  end

  def self.cached_journals_for(user)
    Rails.cache.fetch([name, 'journals', user.current_role]){ TrialPolicy::Scope.new(user, Trial).resolve.joins(:paper).pluck('papers.journal').uniq.compact.sort }
  end

  scope :for_author,      -> (author)  { where(author_id: author) }
  scope :for_journal,     -> (journal) { where(journal: journal) }

  def author_name
    author.try(:last_name)
  end

  def formatted_citation
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(citation).html_safe
  end

  def self.cached_all_for_select
    Rails.cache.fetch [self, 'all-for-select'] do
      Struct.new 'PaperForSelect', :id, :display
      order(:source_id).to_a.map do |p|
        Struct::PaperForSelect.new p.source_id, [p.source_id, p.title.truncate(80, separator: ' ')].join(' - ')
      end
    end
  end

  private

  def normalize_values
    self.journal = nil if journal.blank?
  end

  def flush_cache
    Rails.cache.delete([self.class.name, 'journals'])
    Rails.cache.delete([self.class.name, 'all-for-select'])
    Rails.cache.delete(['Author', 'having-papers'])
    Rails.cache.delete(['Author', 'names-having-papers'])
    User.roles.values.each do |role|
      Rails.cache.delete([self.class.name, 'journals', role])
      Rails.cache.delete(['Author', 'having-papers', role])
      Rails.cache.delete(['Author', 'names-having-papers', role])
    end
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy, :download]

  def show
  end

  def new
    @paper = Paper.new
    @paper.trials.build
  end

  def edit
  end

  def create
    @author = Author.find_or_create_from params[:paper][:author_name]
    @paper = @author.papers.build paper_attributes

    respond_to do |format|
      if @paper.save
        format.html {
          if params[:commit] == 'Create and Add Another'
            redirect_to new_paper_path, notice: ['Paper was successfully created.', view_context.link_to('view', @paper)].join('&nbsp;').html_safe
          else
            redirect_to @paper, notice: 'Paper was successfully created.'
          end
        }
        format.json { render action: 'show', status: :created, location: @paper }
      else
        format.html { render action: 'new' }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    unless @paper.author.last_name == params[:paper][:author_name]
      @paper.author = Author.find_or_create_from params[:paper][:author_name]
    end

    respond_to do |format|
      if @paper.update(paper_attributes)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :no_content }
    end
  end

  def download
    send_data (open @paper.document.url).read,
      type: @paper.document.file.content_type,
      filename: @paper.filename,
      disposition: 'attachment'
  rescue
    raise ActionController::RoutingError.new('Not Found')
  end

  private
    def set_paper
      @paper = current_resource
      authorize! @paper
    end

    def current_resource
      if params[:action] == 'create'
        @current_resource ||= params[:paper] if params[:paper]
      else
        @current_resource ||= Paper.find(params[:id]) if params[:id]
      end
    end

    def paper_attributes
      params.require(:paper).permit *policy(@paper || Paper).permitted_attributes
    end
end

app/helpers/papers_helper.rb
module PapersHelper
  def render_tags(tag_list, current_scope = {})
    tag_list.map do |tag|
      tags = current_scope.has_key?(:tag) ? current_scope[:tag] : []
      #link_to tag, current_scope.merge({tag: tags | [tag]}), class: 'btn btn-xs btn-default'
      content_tag :span, tag, class: 'label label-default'
    end.join("&nbsp;").html_safe
  end
end

app/views/papers/_detail_table.html.haml
%table.table.table-condensed.table-no-top-border.detail-table
  %thead
  %tbody
    %tr
      %th Lead Author
      %td= paper.author_name

    %tr
      %th Reference
      %td= paper.formatted_citation.html_safe

    %tr
      %th Literature Type
      %td= paper.literature_type

    %tr
      %th Product
      %td= paper.product

    %tr
      %th Location
      %td= paper.location

app/views/papers/_form.html.haml
= form_for @paper, html: { class: 'form-horizontal', multipart: true } do |f|
  = render partial: 'shared/form_errors', locals: { resource: @paper }

  %fieldset
    .form-group
      = f.label :source_id, 'Source #', class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :source_id, class: 'form-control'

    .form-group
      = f.label :title, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group
      = f.label :author_name, 'Author', class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :author_name, class: 'form-control autocomplete', data: { authors: Author.cached_names }

    .form-group
      = f.label :citation, 'Reference', class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_area :citation, class: 'form-control'
        %span.help-block To italicize text, surround it with asterisks (*).

    .form-group
      = f.label :literature_type, 'Literature Type', class: 'control-label col-sm-2'
      .col-sm-10
        = f.collection_select :literature_type, Paper::LITERATURE_TYPES, :to_s, :titleize, {}, class: 'form-control'

    .form-group
      = f.label :product, 'Product', class: 'control-label col-sm-2'
      .col-sm-10
        = f.collection_select :product, Paper::PRODUCTS, :to_s, :to_s, {}, class: 'form-control'

    .form-group
      = f.label :journal, 'Peer Reviewed Journal', class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :journal, class: 'form-control autocomplete', data: { journals: Paper.cached_journals }

    .form-group
      = f.label :location, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :location, class: 'form-control'

    .form-group
      = f.label :document, class: 'control-label col-sm-2'
      .col-md-10
        = f.file_field :document

  = f.fields_for :trials do |tf|
    %fieldset
      %legend= "Trial #{tf.object.source_sub_id || 'A'}"

      .form-group
        = tf.label :source_sub_id, 'Trial Letter', class: 'control-label col-sm-2'
        .col-sm-10
          .input-group
            %span.input-group-addon
              %span.paper-id-addon
              = "-"
            = tf.text_field :source_sub_id, disabled: true, class: 'form-control'

      .form-group
        = tf.label :level, class: 'control-label col-sm-2'
        .col-sm-10
          - tf.object.level = nil if tf.object.new_record? && tf.object.errors.none? && f.object.errors.none?
          = tf.collection_select :level, policy(Trial).accessible_levels.keys.map(&:to_s), :to_s, Proc.new{|l| Trial.display_level(l) }, {include_blank: 'Choose...'}, class: 'form-control'

      .form-group
        = tf.label :year, class: 'control-label col-sm-2'
        .col-sm-10
          = tf.text_field :year, class: 'form-control'

      .form-group
        = tf.label :summary, class: 'control-label col-sm-2'
        .col-sm-10
          = tf.text_area :summary, class: 'form-control'

      .form-group
        = tf.label :species_list, 'Species', class: 'control-label col-sm-2'
        .col-sm-10
          = tf.text_field :species_list, class: 'form-control species-select2', value: tf.object.species_list.to_s, data: { tags: Trial.cached_species }
          %span.help-block Separate with commas

      .form-group
        = tf.label :focus_list, 'Focus(es)', class: 'control-label col-sm-2'
        .col-sm-10
          = tf.text_field :focus_list, class: 'form-control focuses-select2', value: tf.object.focus_list.to_s, data: { tags: Trial.cached_focuses }
          %span.help-block Separate with commas

      .form-group
        = tf.label :calculation_list, 'Included in X Calculations', class: 'control-label col-sm-2'
        .col-sm-10
          = tf.text_field :calculation_list, class: 'form-control calculations-select2', value: tf.object.calculation_list.to_s, data: { tags: Trial.cached_calculations }
          %span.help-block Separate with commas

      .form-group
        = tf.label :dose, class: 'control-label col-sm-2'
        .col-sm-10
          = tf.text_field :dose, class: 'form-control'

      .form-group
        = tf.label :forage, 'Forage', class: 'control-label col-sm-2'
        .col-sm-10
          = tf.text_field :forage, class: 'form-control'

      .form-group
        = tf.label :concentrate, 'Concentrate', class: 'control-label col-sm-2'
        .col-sm-10
          = tf.text_field :concentrate, class: 'form-control'

  %fieldset
    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit class: 'btn btn-primary'
        = f.submit 'Create and Add Another', class: 'btn btn-primary' if @paper.new_record?
        = link_to 'Cancel', papers_path, class: 'btn btn-inverse'

app/views/papers/_trial.html.haml
%table.table.table-condensed.table-no-top-border.detail-table
  %thead
  %tbody
    - if policy(Trial).show_level?
      %tr
        %th Level
        %td= trial.display_level

    %tr
      %th Year
      %td= trial.year

    %tr
      %th Summary
      %td= trial.summary

    %tr
      %th Dose
      %td= trial.dose

    %tr
      %th Species
      %td= trial.expanded_species_list

    %tr
      %th Focus(es)
      %td= trial.cached_focus_list

    %tr
      %th Forage
      %td= trial.forage

    %tr
      %th Concentrate
      %td= trial.concentrate

    - if trial.performance_measures.any?
      %tr
        %th{colspan: 2} Performance Measures

app/views/papers/_trial_box.html.haml
.box.trial-box{data: { trial: trial.id }}
  .box-header
    %h2
      %i.fa.fa-flask
      = a_space "Trial"
      %span.trial-id= trial.source_sub_id

    .box-icon
      - if spotlight && spotlight.id != trial.id
        %a.btn-maximize{href: '#'}
          %i.fa.fa-chevron-down
      - else
        %a.btn-minimize{href: '#'}
          %i.fa.fa-chevron-up

    - if policy(trial).destroy?
      .box-icon
        = link_to [trial.paper, trial], title: "Delete Trial", data: { confirm: 'Are you sure?' }, method: :delete, remote: true do
          %i.fa.fa-fw.fa-trash-o
          
    - if policy(trial).edit?
      .box-icon
        = link_to edit_paper_trial_path(trial.paper, trial), remote: true, title: 'Edit' do
          %i.fa.fa-pencil
    
  .box-content
    %span.trial-box-show
      = render partial: 'papers/trial', locals: { trial: trial }

    %span.trial-box-edit

    .row.performance-measures-row
      - trial.performance_measures.each do |measure|
        = render partial: 'measures/measure', locals: { measure: measure, editable: policy(trial).edit? }

      - if policy(trial).edit?
        .col-md-3.col-xs-6.col-xxs-12.new-performance-measure-btn-container
          = link_to new_performance_measure_path(trial: trial.id), remote: true, class: 'quick-button' do
            %i.fa.fa-plus
            %p New

app/views/papers/_trial_box_row.html.haml
.row
  .col-md-12
    = render partial: 'papers/trial_box', locals: { trial: trial, spotlight: spotlight }

app/views/papers/edit.html.haml
- title "Edit Literature"

.row
  .col-md-12
    .box
      .box-header
        %h2
          %i.fa.fa-file-text
          = @paper.source_id
      .box-content
        = render 'form'

app/views/papers/index.html.haml
- title 'Papers', false

.row
  .col-md-12
    .box.full-color
      .box-content
        = form_tag papers_path, method: :get, id: 'paper_filter' do
          .row
            .col-md-3.text-center
              %h4.white Species
              = select_tag :species, options_for_select(Paper.cached_species, params[:species]), include_blank: true, class: 'form-control'

            .col-md-3.text-center
              %h4.white Focus
              = select_tag :focus, options_for_select(Paper.cached_focuses, params[:focus]), include_blank: true, class: 'form-control'

            .col-md-3.text-center
              %h4.white Author
              = select_tag :author, options_from_collection_for_select(Author.cached_all, :id, :last_name, params[:author]), include_blank: true, class: 'form-control'

            .col-md-3.text-center
              %h4.white Peer Reviewed
              = select_tag :journal, options_for_select(Paper.cached_journals, params[:journal]), include_blank: true, class: 'form-control'

.row
  .col-md-12
    .table-responsive
      %table.table.table-condensed.table-bordered
        %thead
          - if @papers.any?
            %tr
              %th{style: 'width: 20%;'} Reference
              %th.c= sortable :year
              %th.c= sortable :literature_type, 'Literature Type'
              %th.c= sortable :journal, 'Peer Reviewed Journal'
              %th.c Species
              %th.c Focus
              %th.c Dose
              / %th.c Forage %
              / %th.c Concentrate %
              %th.c Summary
              %th.c

        %tbody
          - if @papers.any?
            = render @papers
          - else
            %tr.warning
              %td.c{colspan: 9} 
                %br/
                There are no research papers that match the current filters.
                %br/
                %br/

      = will_paginate @papers

%br/

- if policy(Paper).create?
  .row
    .col-md-12
      = link_to new_paper_path, class: 'btn btn-primary' do
        %i.fa.fa-plus
        = p_space "Add Paper"

app/views/papers/new.html.haml
- title "New Literature"

.row
  .col-md-12
    .box
      .box-header
        %h2
          %i.fa.fa-file-text
      .box-content
        = render 'form'

app/views/papers/show.html.haml
- title @paper.title, false

- breadcrumbs ['Literature', papers_path], @paper.source_id, show: false

.row
  .col-md-3
    = yield :breadcrumbs

  .col-md-9.btn-row.text-right
    - if @paper.document.present?
      = link_to download_paper_path(@paper), title: "Download Tech Sheet", class: 'btn btn-sm btn-success', data: { 'no-turbolink' => true } do
        %i.fa.fa-cloud-download
        = p_space 'Download Tech Sheet'
    - if policy(Trial).new?
      = link_to new_paper_trial_path(@paper), title: "Add Trial", remote: true, class: "btn btn-sm btn-primary" do
        %i.fa.fa-plus
        = p_space 'Add Trial'
    - if policy(Supplemental).new?
      = link_to new_paper_supplemental_path(@paper), title: "Add Supplemental", class: "btn btn-sm btn-primary" do
        %i.fa.fa-plus
        = p_space 'Add Supplemental Document'
    - if policy(@paper).edit?
      = link_to edit_paper_path(@paper), title: "Edit Paper", class: "btn btn-sm btn-warning" do
        %i.fa.fa-pencil
        = p_space 'Edit'
    - if policy(@paper).destroy?
      = link_to @paper, title: "Remove", class: "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' }, method: :delete do
        %i.fa.fa-trash-o
        = p_space 'Remove'

.row
  .col-md-12
    %h1= @paper.title

%br/

.row
  .col-md-12
    = render partial: 'papers/detail_table', locals: { paper: @paper }

- policy_scope(@paper.trials).order(:source_sub_id).each do |trial|
  = render partial: 'papers/trial_box_row', locals: { trial: trial, spotlight: @trial || nil }

- if (supplementals = policy_scope(@paper.supplementals).order(:source_sub_id)).any?
  %h2.supplementals-subheader Supplemental Documents
  = render partial: 'supplementals/display_box', locals: { paper: @paper, supplementals: supplementals }